
"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“ABCDEFGHIJKLMNOPQRSTUVWXYZ”		

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“ABCD”							

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	"IJKLMNOPQRSTUVWXYZ"				

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“EFGHIJKLMNOP”					

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“ADGJMPSVY”						

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“ZYXWVUTSRQPONMLKJIHGFEDCBA”		

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“EHKNQTW”						

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“XUROLIF”						



exemple : “ABCDEFGHIJKLMNOPQRSTUVWXYZ”[:1] -> “A”




SOLUCE

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“ABCDEFGHIJKLMNOPQRSTUVWXYZ”		[:]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“ABCD”										[:4]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	"IJKLMNOPQRSTUVWXYZ"					[8:]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	-> 	“EFGHIJKLMNOP”							[4:16]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“ADGJMPSVY”								[::3]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“ZYXWVUTSRQPONMLKJIHGFEDCBA”		[::-1]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“EHKNQTW”									[4:23:3]

"ABCDEFGHIJKLMNOPQRSTUVWXYZ"	->	“XUROLIF”									[23:4:-3]